import { modalOnay } from '@/lib/dialog'
import { useEffect, useState, type ReactNode } from 'react'
import { useTranslation } from 'react-i18next'
import { api, apiHata } from '@/lib/api'

const input = 'w-full rounded-lg border border-slate-300 bg-white px-2.5 py-1.5 text-xs dark:border-slate-600 dark:bg-slate-900 dark:text-slate-200'
const btn = 'rounded-lg bg-slate-800 px-3 py-1.5 text-xs font-medium text-white hover:bg-slate-700 disabled:opacity-40 dark:bg-slate-200 dark:text-slate-900'

function Kart({ title, desc, children, durum }: { title: string; desc: string; children: ReactNode; durum?: ReactNode }) {
  return <div className="h-full rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900/40">
    <div className="flex items-start justify-between gap-2"><div><h3 className="text-sm font-semibold text-slate-900 dark:text-slate-100">{title}</h3><p className="mt-1 text-xs text-slate-500 dark:text-slate-400">{desc}</p></div>{durum}</div>
    <div className="mt-3">{children}</div>
  </div>
}
function Mesaj({ hata, basari }: { hata?: string; basari?: string }) { return <>{hata && <p className="mb-2 rounded bg-red-50 p-2 text-xs text-red-700 dark:bg-red-900/20 dark:text-red-300">{hata}</p>}{basari && <p className="mb-2 rounded bg-emerald-50 p-2 text-xs text-emerald-700 dark:bg-emerald-900/20 dark:text-emerald-300">{basari}</p>}</> }
function Rozet({ iyi, children }: { iyi: boolean; children: ReactNode }) { return <span className={`shrink-0 rounded-full px-2 py-0.5 text-[10px] font-medium ${iyi ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-300' : 'bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-300'}`}>{children}</span> }
const gb = (v: number) => `${(v / 1073741824).toFixed(1)} GB`

type Guvenlik = { aktif:boolean; otomatik_reboot:boolean; bekleyen:number; son_calisma:string; sonraki_calisma:string; calisiyor:boolean; destekli:boolean }
export function GuvenlikGuncellemeAyari() {
  const { t } = useTranslation('GelismisSunucuAyarlari'); const [d,setD]=useState<Guvenlik>(); const [aktif,setAktif]=useState(false); const [reboot,setReboot]=useState(false); const [msg,setMsg]=useState(''); const [busy,setBusy]=useState(false)
  const yukle=()=>api.get<Guvenlik>('/system/bakim/guvenlik').then(r=>{setD(r.data);setAktif(r.data.aktif);setReboot(r.data.otomatik_reboot)}).catch(e=>setMsg(apiHata(e,t('common.load_failed'))))
  useEffect(()=>{ void yukle() },[]) // eslint-disable-line react-hooks/exhaustive-deps
  const kaydet=async()=>{setBusy(true);setMsg('');try{await api.put('/system/bakim/guvenlik',{aktif,otomatik_reboot:reboot});setMsg(t('common.saved'));yukle()}catch(e){setMsg(apiHata(e,t('common.save_failed')))}finally{setBusy(false)}}
  return <Kart title={t('security.title')} desc={t('security.desc')} durum={d&&<Rozet iyi={d.bekleyen===0}>{t('security.pending',{count:d.bekleyen})}</Rozet>}><Mesaj hata={msg&&!msg.includes(t('common.saved'))?msg:''} basari={msg.includes(t('common.saved'))?msg:''}/><div className="space-y-2 text-xs text-slate-600 dark:text-slate-300"><label className="flex gap-2"><input type="checkbox" checked={aktif} onChange={e=>setAktif(e.target.checked)}/>{t('security.enable')}</label><label className="flex gap-2"><input type="checkbox" checked={reboot} onChange={e=>setReboot(e.target.checked)} disabled={!aktif}/>{t('security.auto_reboot')}</label>{d?.son_calisma&&<p>{t('security.last')}: {d.son_calisma}</p>}<button className={btn} onClick={kaydet} disabled={busy||!d?.destekli}>{t('common.save')}</button></div></Kart>
}

type Kimlik={hostname:string;adresler:string[];hostname_adresleri:string[];ptr:Record<string,string[]>;ileri_eslesiyor:boolean;ptr_eslesiyor:boolean}
export function SunucuKimlikDNS() { const{t}=useTranslation('GelismisSunucuAyarlari');const[d,setD]=useState<Kimlik>();const[h,setH]=useState('');const yukle=()=>api.get<Kimlik>('/system/bakim/kimlik-dns').then(r=>{setD(r.data);setH('')}).catch(e=>setH(apiHata(e,t('common.load_failed'))))
 useEffect(()=>{ void yukle() },[]) // eslint-disable-line react-hooks/exhaustive-deps
 return <Kart title={t('identity.title')} desc={t('identity.desc')} durum={d&&<Rozet iyi={d.ileri_eslesiyor&&d.ptr_eslesiyor}>{d.ileri_eslesiyor&&d.ptr_eslesiyor?t('identity.ok'):t('identity.warning')}</Rozet>}><Mesaj hata={h}/>{d&&<div className="space-y-1 text-xs text-slate-600 dark:text-slate-300"><p>{t('identity.hostname')}: <code>{d.hostname}</code></p><p>{t('identity.ips')}: <code>{d.adresler.join(', ')||'—'}</code></p><p>{t('identity.forward')}: <code>{d.hostname_adresleri.join(', ')||'—'}</code></p>{d.adresler.map(ip=><p key={ip}>PTR {ip}: <code>{d.ptr[ip]?.join(', ')||'—'}</code></p>)}<button className={btn} onClick={yukle}>{t('common.refresh')}</button></div>}</Kart> }

type Depo={disk_esik:number;inode_esik:number;disk_yuzde:number;inode_yuzde:number;disk_toplam:number;disk_bos:number;disk_uyari:boolean;inode_uyari:boolean;buyuk_dizinler:Record<string,number>}
export function DepolamaAyari(){const{t}=useTranslation('GelismisSunucuAyarlari');const[d,setD]=useState<Depo>();const[de,setDe]=useState(80);const[ie,setIe]=useState(85);const[m,setM]=useState('');const yukle=()=>api.get<Depo>('/system/bakim/depolama').then(r=>{setD(r.data);setDe(r.data.disk_esik);setIe(r.data.inode_esik)}).catch(e=>setM(apiHata(e,t('common.load_failed'))));useEffect(()=>{ void yukle() },[]) // eslint-disable-line react-hooks/exhaustive-deps
const save=async()=>{try{await api.put('/system/bakim/depolama',{disk_esik:de,inode_esik:ie});setM(t('common.saved'));yukle()}catch(e){setM(apiHata(e,t('common.save_failed')))}};return <Kart title={t('storage.title')} desc={t('storage.desc')} durum={d&&<Rozet iyi={!d.disk_uyari&&!d.inode_uyari}>{d.disk_uyari||d.inode_uyari?t('storage.warning'):t('storage.ok')}</Rozet>}><Mesaj hata={m&&!m.includes(t('common.saved'))?m:''} basari={m.includes(t('common.saved'))?m:''}/>{d&&<div className="space-y-2 text-xs text-slate-600 dark:text-slate-300"><p>{t('storage.disk')}: %{d.disk_yuzde.toFixed(1)} · {gb(d.disk_toplam-d.disk_bos)} / {gb(d.disk_toplam)}</p><p>{t('storage.inode')}: %{d.inode_yuzde.toFixed(1)}</p><div className="grid grid-cols-2 gap-2"><label>{t('storage.disk_limit')}<input className={input} type="number" min="50" max="99" value={de} onChange={e=>setDe(+e.target.value)}/></label><label>{t('storage.inode_limit')}<input className={input} type="number" min="50" max="99" value={ie} onChange={e=>setIe(+e.target.value)}/></label></div><p>{Object.entries(d.buyuk_dizinler).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`${k}: ${gb(v)}`).join(' · ')}</p><button className={btn} onClick={save}>{t('common.save')}</button></div>}</Kart>}

type Reboot={gerekli:boolean;calisan_kernel:string;son_kernel:string;acilis_zamani:string;calisma_suresi_saniye:number}
export function RebootBilgisi(){const{t}=useTranslation('GelismisSunucuAyarlari');const[d,setD]=useState<Reboot>();const[h,setH]=useState('');const yukle=()=>api.get<Reboot>('/system/bakim/reboot').then(r=>setD(r.data)).catch(e=>setH(apiHata(e,t('common.load_failed'))));useEffect(()=>{ void yukle() },[]) // eslint-disable-line react-hooks/exhaustive-deps
return <Kart title={t('reboot.title')} desc={t('reboot.desc')} durum={d&&<Rozet iyi={!d.gerekli}>{d.gerekli?t('reboot.required'):t('reboot.not_required')}</Rozet>}><Mesaj hata={h}/>{d&&<div className="space-y-1 text-xs text-slate-600 dark:text-slate-300"><p>{t('reboot.boot')}: {new Date(d.acilis_zamani).toLocaleString()}</p><p>{t('reboot.uptime')}: {Math.floor(d.calisma_suresi_saniye/86400)} {t('reboot.days')}</p><p>{t('reboot.running')}: <code>{d.calisan_kernel}</code></p>{d.gerekli&&<p>{t('reboot.latest')}: <code>{d.son_kernel}</code></p>}<button className={btn} onClick={yukle}>{t('common.refresh')}</button></div>}</Kart>}

type Journal={kullanim_byte:number;maksimum_mb:number;kalici:boolean}
export function JournalAyari(){const{t}=useTranslation('GelismisSunucuAyarlari');const[d,setD]=useState<Journal>();const[max,setMax]=useState(500);const[m,setM]=useState('');const yukle=()=>api.get<Journal>('/system/bakim/journal').then(r=>{setD(r.data);if(r.data.maksimum_mb)setMax(r.data.maksimum_mb)}).catch(e=>setM(apiHata(e,t('common.load_failed'))));useEffect(()=>{ void yukle() },[]) // eslint-disable-line react-hooks/exhaustive-deps
const save=async()=>{try{await api.put('/system/bakim/journal',{maksimum_mb:max});setM(t('common.saved'));yukle()}catch(e){setM(apiHata(e,t('common.save_failed')))}};const clean=async()=>{if(!(await modalOnay(t('journal.confirm'))))return;try{await api.post('/system/bakim/journal/temizle',{koru_mb:max});setM(t('journal.cleaned'));yukle()}catch(e){setM(apiHata(e,t('journal.clean_failed')))}};return <Kart title={t('journal.title')} desc={t('journal.desc')}><Mesaj hata={m&&!m.includes(t('common.saved'))&&!m.includes(t('journal.cleaned'))?m:''} basari={m.includes(t('common.saved'))||m.includes(t('journal.cleaned'))?m:''}/>{d&&<div className="space-y-2 text-xs text-slate-600 dark:text-slate-300"><p>{t('journal.usage')}: {gb(d.kullanim_byte)} · {d.kalici?t('journal.persistent'):t('journal.volatile')}</p><label>{t('journal.limit')}<input className={input} type="number" min="100" max="10240" value={max} onChange={e=>setMax(+e.target.value)}/></label><div className="flex gap-2"><button className={btn} onClick={save}>{t('common.save')}</button><button className={btn} onClick={clean}>{t('journal.clean')}</button></div></div>}</Kart>}

type DNS={sunucular:string[];arama_alanlari:string[];yonetici:string;baglanti:string}
export function DNSCozumleyiciAyari(){const{t}=useTranslation('GelismisSunucuAyarlari');const[d,setD]=useState<DNS>();const[ns,setNs]=useState('');const[domain,setDomain]=useState('cloud.sanalcp.com');const[m,setM]=useState('');const yukle=()=>api.get<DNS>('/system/bakim/dns').then(r=>{setD(r.data);setNs(r.data.sunucular.join(', '))}).catch(e=>setM(apiHata(e,t('common.load_failed'))));useEffect(()=>{ void yukle() },[]) // eslint-disable-line react-hooks/exhaustive-deps
const test=async()=>{try{const r=await api.post<{adresler:string[]}>('/system/bakim/dns/test',{alan_adi:domain});setM(t('dns.test_ok',{ips:r.data.adresler.join(', ')}))}catch(e){setM(apiHata(e,t('dns.test_failed')))}};const save=async()=>{if(!(await modalOnay(t('dns.confirm'))))return;try{await api.put('/system/bakim/dns',{sunucular:ns.split(',').map(x=>x.trim()).filter(Boolean)});setM(t('common.saved'));yukle()}catch(e){setM(apiHata(e,t('common.save_failed')))}};return <Kart title={t('dns.title')} desc={t('dns.desc')}><Mesaj hata={m&&(m.includes(t('common.save_failed'))||m.includes(t('dns.test_failed')))?m:''} basari={m&&!m.includes(t('common.save_failed'))&&!m.includes(t('dns.test_failed'))?m:''}/>{d&&<div className="space-y-2 text-xs text-slate-600 dark:text-slate-300"><p>{d.yonetici}{d.baglanti?` · ${d.baglanti}`:''}</p><label>{t('dns.servers')}<input className={input} value={ns} onChange={e=>setNs(e.target.value)}/></label><div className="flex gap-2"><input className={input} value={domain} onChange={e=>setDomain(e.target.value)}/><button className={btn} onClick={test}>{t('dns.test')}</button></div><button className={btn} onClick={save}>{t('common.save')}</button></div>}</Kart>}

type Swap={toplam_byte:number;kullanilan_byte:number;swappiness:number;kaynaklar:string[]}
export function SwapAyari(){const{t}=useTranslation('GelismisSunucuAyarlari');const[d,setD]=useState<Swap>();const[sw,setSw]=useState(60);const[size,setSize]=useState(2048);const[m,setM]=useState('');const yukle=()=>api.get<Swap>('/system/bakim/swap').then(r=>{setD(r.data);setSw(r.data.swappiness)}).catch(e=>setM(apiHata(e,t('common.load_failed'))));useEffect(()=>{ void yukle() },[]) // eslint-disable-line react-hooks/exhaustive-deps
const save=async(create=false)=>{if(create&&!(await modalOnay(t('swap.confirm',{size}))))return;try{await api.put('/system/bakim/swap',{swappiness:sw,olustur_mb:create?size:0});setM(t('common.saved'));yukle()}catch(e){setM(apiHata(e,t('common.save_failed')))}};return <Kart title={t('swap.title')} desc={t('swap.desc')} durum={d&&<Rozet iyi={d.toplam_byte>0}>{d.toplam_byte>0?t('swap.active'):t('swap.none')}</Rozet>}><Mesaj hata={m&&!m.includes(t('common.saved'))?m:''} basari={m.includes(t('common.saved'))?m:''}/>{d&&<div className="space-y-2 text-xs text-slate-600 dark:text-slate-300"><p>{t('swap.usage')}: {gb(d.kullanilan_byte)} / {gb(d.toplam_byte)} {(d.kaynaklar ?? []).join(', ')}</p><label>Swappiness<input className={input} type="number" min="0" max="100" value={sw} onChange={e=>setSw(+e.target.value)}/></label><button className={btn} onClick={()=>save(false)}>{t('common.save')}</button>{d.toplam_byte===0&&<div className="flex gap-2"><input className={input} type="number" min="256" max="32768" value={size} onChange={e=>setSize(+e.target.value)}/><button className={btn} onClick={()=>save(true)}>{t('swap.create')}</button></div>}</div>}</Kart>}
