CREATE TABLE IF NOT EXISTS cloudflare_settings (
  id TINYINT UNSIGNED NOT NULL PRIMARY KEY,
  api_token VARCHAR(1024) NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS cloudflare_zones (
  domain_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  zone_id VARCHAR(64) NOT NULL,
  zone_name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT '',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_cloudflare_zone_domain FOREIGN KEY (domain_id) REFERENCES domains(id) ON DELETE CASCADE,
  UNIQUE KEY uq_cloudflare_zone_id (zone_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
