import { modalGirdi, modalOnay } from '@/lib/dialog'
import { useCallback, useEffect, useState } from 'react'
import { Link, useParams, useSearchParams } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import Breadcrumb from '@/components/Breadcrumb'
import { api, apiHata } from '@/lib/api'

type Kontrol = { ad: string; ok: boolean; detay: string }
type Durum = { surum: string; php: string; bakim: boolean; scheduler: boolean; queue_worker: boolean; kontroller: Kontrol[] }
type EnvItem = { gizli: boolean; dolu?: boolean; deger?: string }
type Job = { id:number; tur:string; komut:string; durum:string; ilerleme:number; mesaj:string; cikti:string; recovery_file:string; created_at:string }

export default function DomainLaravelPage() {
  const { t } = useTranslation(['DomainLaravelPage', 'common'])
  const { id } = useParams(); const [params, setParams] = useSearchParams()
  const [dizin, setDizin] = useState(params.get('dizin') || 'public_html')
  const [durum, setDurum] = useState<Durum | null>(null); const [env, setEnv] = useState<Record<string, EnvItem>>({})
  const [jobs,setJobs]=useState<Job[]>([]); const [migrate,setMigrate]=useState(false)
  const [kurulumlar,setKurulumlar]=useState<string[]>([])
  const [hata, setHata] = useState(''); const [ok, setOk] = useState(''); const [mesgul, setMesgul] = useState(''); const [cikti, setCikti] = useState('')
  const yukle = useCallback(async (hedef = dizin) => { if (!id) return; setHata(''); try { const [d,e,j] = await Promise.all([api.get<Durum>(`/domains/${id}/laravel/durum`,{params:{dizin:hedef}}),api.get<{degiskenler:Record<string,EnvItem>}>(`/domains/${id}/laravel/env`,{params:{dizin:hedef}}),api.get<Job[]>(`/domains/${id}/laravel/jobs`)]); setDurum(d.data); setEnv(e.data.degiskenler);setJobs(j.data); setParams({dizin:hedef},{replace:true}) } catch(e){setDurum(null);setHata(apiHata(e,t('not_found')))} },[id,dizin,setParams,t])
  useEffect(()=>{if(!id)return;api.get<{kurulumlar:string[]}>(`/domains/${id}/laravel/discover`).then(r=>{setKurulumlar(r.data.kurulumlar);const hedef=params.get('dizin')||r.data.kurulumlar[0]||'public_html';setDizin(hedef);void yukle(hedef)}).catch(e=>setHata(apiHata(e,t('not_found'))))},[]) // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{if(!jobs.some(j=>['queued','running'].includes(j.durum)))return;const timer=setInterval(()=>void yukle(),2500);return()=>clearInterval(timer)},[jobs,yukle])
  async function artisan(komut:string){setMesgul(komut);setHata('');try{const r=await api.post<{ok:boolean;cikti:string}>(`/domains/${id}/laravel/artisan`,{dizin,komut});setCikti(r.data.cikti||'—');if(!r.data.ok)setHata(t('command_failed'))}catch(e){setHata(apiHata(e))}finally{setMesgul('')}}
  async function bakim(){if(!durum)return;setMesgul('bakim');try{await api.post(`/domains/${id}/laravel/bakim`,{dizin,aktif:!durum.bakim});setOk(t('saved'));await yukle()}catch(e){setHata(apiHata(e))}finally{setMesgul('')}}
  async function envDuzenle(k:string,item:EnvItem){const mevcut=item.gizli?'':(item.deger||'');const deger=await modalGirdi(t(item.gizli?'secret_prompt':'value_prompt',{key:k}),mevcut,{gizli:item.gizli});if(deger===null)return;try{await api.put(`/domains/${id}/laravel/env`,{dizin,anahtar:k,deger});setOk(t('saved'));await yukle()}catch(e){setHata(apiHata(e))}}
  async function envEkle(){const anahtar=await modalGirdi(t('key_prompt'));if(!anahtar)return;await envDuzenle(anahtar.toUpperCase(),{gizli:true,dolu:false})}
  async function isBaslat(tur:'deploy'|'composer',komut=''){if(tur==='deploy'&&!(await modalOnay(t('deploy_confirm'))))return;setMesgul(tur+komut);setHata('');try{await api.post(`/domains/${id}/laravel/${tur}`,tur==='deploy'?{dizin,migrate}:{dizin,komut});setOk(t('job_started'));await yukle()}catch(e){setHata(apiHata(e))}finally{setMesgul('')}}
  async function runtime(tur:'scheduler'|'queue',aktif:boolean){setMesgul(tur);setHata('');try{await api.put(`/domains/${id}/laravel/${tur}`,{dizin,aktif,queue:'default',tries:3,timeout:90});setOk(t('saved'));await yukle()}catch(e){setHata(apiHata(e))}finally{setMesgul('')}}
  return <div className="w-full px-6 py-6"><Breadcrumb items={[{etiket:t('common:home'),href:'/'},{etiket:t('subscription'),href:`/abonelikler/${id}`},{etiket:t('title')}]} />
    <h1 className="text-2xl font-semibold dark:text-white">{t('title')}</h1><p className="mt-1 mb-5 text-sm text-slate-500">{t('subtitle')}</p>
    <form className="flex max-w-xl gap-2 mb-5" onSubmit={e=>{e.preventDefault();void yukle(dizin)}}>{kurulumlar.length?<select className="ta-input flex-1" value={dizin} onChange={e=>{setDizin(e.target.value);void yukle(e.target.value)}}>{kurulumlar.map(k=><option key={k}>{k}</option>)}</select>:<input className="ta-input flex-1" value={dizin} onChange={e=>setDizin(e.target.value)}/>}<button className="ta-primary-button">{t('scan')}</button></form>
    {hata&&<div className="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{hata}</div>}{ok&&<div className="mb-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{ok}</div>}
    {durum&&<><div className="grid grid-cols-2 lg:grid-cols-4 gap-3 mb-5"><Kart ad={t('version')} deger={durum.surum||'—'}/><Kart ad="PHP" deger={durum.php}/><Kart ad={t('scheduler')} deger={durum.scheduler?t('active'):t('inactive')}/><Kart ad={t('queue')} deger={durum.queue_worker?t('active'):t('inactive')}/></div>
      <div className="grid lg:grid-cols-2 gap-5"><section className="rounded-2xl border border-slate-200 dark:border-slate-700 p-5"><h2 className="font-semibold dark:text-white mb-3">{t('health')}</h2>{durum.kontroller.map(k=><div key={k.ad} className="mb-2 text-sm"><span className={k.ok?'text-emerald-500':'text-red-500'}>●</span> <b>{k.ad}</b><div className="ml-4 text-xs text-slate-400">{k.detay}</div></div>)}<button className="ta-primary-button mt-3" disabled={!!mesgul} onClick={()=>void bakim()}>{durum.bakim?t('maintenance_off'):t('maintenance_on')}</button></section>
      <section className="rounded-2xl border border-slate-200 dark:border-slate-700 p-5"><h2 className="font-semibold dark:text-white mb-3">Artisan</h2><div className="flex flex-wrap gap-2">{['about','cache-clear','config-cache','config-clear','route-clear','view-clear','migrate-status'].map(c=><button key={c} className="ta-secondary-button" disabled={!!mesgul} onClick={()=>void artisan(c)}>{mesgul===c?'…':c}</button>)}</div><pre className="mt-4 max-h-48 overflow-auto rounded bg-slate-950 p-3 text-xs text-slate-300">{cikti||t('no_output')}</pre></section></div>
      <div className="mt-5 grid lg:grid-cols-2 gap-5"><section className="rounded-2xl border border-slate-200 dark:border-slate-700 p-5"><h2 className="font-semibold dark:text-white mb-2">{t('deploy')}</h2><p className="text-xs text-slate-400 mb-3">{t('deploy_note')}</p><label className="mb-3 flex gap-2 text-sm"><input type="checkbox" checked={migrate} onChange={e=>setMigrate(e.target.checked)}/>{t('run_migrations')}</label><div className="flex flex-wrap gap-2"><button className="ta-primary-button" disabled={!!mesgul} onClick={()=>void isBaslat('deploy')}>{t('deploy_start')}</button>{['install','update','dump-autoload'].map(c=><button key={c} className="ta-secondary-button" disabled={!!mesgul} onClick={()=>void isBaslat('composer',c)}>Composer {c}</button>)}</div></section>
      <section className="rounded-2xl border border-slate-200 dark:border-slate-700 p-5"><h2 className="font-semibold dark:text-white mb-3">{t('runtime')}</h2><div className="flex flex-wrap gap-2"><button className="ta-secondary-button" disabled={!!mesgul} onClick={()=>void runtime('scheduler',!durum.scheduler)}>{durum.scheduler?t('scheduler_off'):t('scheduler_on')}</button><button className="ta-secondary-button" disabled={!!mesgul} onClick={()=>void runtime('queue',!durum.queue_worker)}>{durum.queue_worker?t('queue_off'):t('queue_on')}</button></div></section></div>
      <section className="mt-5 rounded-2xl border border-slate-200 dark:border-slate-700 p-5"><div className="flex justify-between"><h2 className="font-semibold dark:text-white mb-1">.env</h2><button className="text-xs text-brand-600" onClick={()=>void envEkle()}>{t('add_variable')}</button></div><p className="mb-3 text-xs text-slate-400">{t('env_note')}</p><div className="grid md:grid-cols-2 gap-2">{Object.entries(env).sort().map(([k,v])=><button key={k} onClick={()=>void envDuzenle(k,v)} className="flex justify-between rounded-lg border border-slate-200 dark:border-slate-700 p-2 text-left text-xs"><b>{k}</b><span className="text-slate-400">{v.gizli?(v.dolu?'••••••':t('empty')):(v.deger||t('empty'))}</span></button>)}</div></section></>}
      {durum&&<section className="mt-5 rounded-2xl border border-slate-200 dark:border-slate-700 p-5"><h2 className="font-semibold dark:text-white mb-3">{t('history')}</h2><div className="space-y-2">{jobs.map(j=><details key={j.id} className="rounded-lg border border-slate-200 dark:border-slate-700 p-3 text-xs"><summary className="cursor-pointer flex justify-between"><span>#{j.id} · {j.tur} · {j.komut}</span><span>{j.ilerleme}% · {j.durum}</span></summary><p className="mt-2 text-slate-500">{j.mesaj}</p>{j.recovery_file&&<p className="text-slate-400">{t('recovery')}: {j.recovery_file}</p>}<pre className="mt-2 max-h-56 overflow-auto bg-slate-950 p-3 text-slate-300">{j.cikti||'—'}</pre></details>)}</div></section>}
    <Link className="mt-6 inline-block text-sm text-slate-500" to={`/abonelikler/${id}`}>{t('back')}</Link></div>
}
function Kart({ad,deger}:{ad:string;deger:string}){return <div className="rounded-2xl border border-slate-200 dark:border-slate-700 p-4"><div className="text-xs text-slate-400">{ad}</div><div className="mt-1 font-semibold dark:text-white">{deger}</div></div>}
