import { modalOnay } from '@/lib/dialog'
import { useEffect, useState } from 'react'
import { useParams, Link } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { api, apiHata } from '@/lib/api'
import Breadcrumb from '@/components/Breadcrumb'
type Domain={id:number;alan_adi:string};type Ortam={id:number;staging_domain_id:number;alan_adi:string;durum:string;olusturma:string;son_push:string}
export default function DomainKopyaPage(){
 const {t}=useTranslation(['DomainKopyaPage','common']),{id}=useParams();const [domain,setDomain]=useState<Domain|null>(null),[liste,setListe]=useState<Ortam[]>([]),[alanAdi,setAlanAdi]=useState(''),[dosyalar,setDosyalar]=useState(true),[veritabani,setVeritabani]=useState(false),[busy,setBusy]=useState(false),[hata,setHata]=useState<string|null>(null),[ok,setOk]=useState<string|null>(null)
 function yukle(){if(!id)return;api.get<Domain>(`/domains/${id}`).then(r=>{setDomain(r.data);setAlanAdi(a=>a||`staging.${r.data.alan_adi}`)});api.get<Ortam[]>(`/domains/${id}/kopya`).then(r=>setListe(r.data||[])).catch(e=>setHata(apiHata(e)))}useEffect(yukle,[id])
 async function olustur(){setBusy(true);setHata(null);setOk(null);try{await api.post(`/domains/${id}/kopya`,{alan_adi:alanAdi});setOk(t('created'));yukle()}catch(e){setHata(apiHata(e,t('create_failed')))}finally{setBusy(false)}}
 async function push(){if(!(await modalOnay(t('confirm_push'))))return;setBusy(true);setHata(null);setOk(null);try{const {data}=await api.post(`/domains/${id}/kopya/canliya-gonder`,{dosyalar,veritabani});setOk(t('pushed',{backup:data.kurtarma_yedegi}));yukle()}catch(e){setHata(apiHata(e,t('push_failed')))}finally{setBusy(false)}}
 async function sil(){if(!(await modalOnay(t('confirm_delete'))))return;setBusy(true);try{await api.delete(`/domains/${id}/kopya`);setOk(t('deleted'));yukle()}catch(e){setHata(apiHata(e,t('delete_failed')))}finally{setBusy(false)}}const ortam=liste[0]
 return <div className="px-6 py-5"><Breadcrumb items={[{etiket:t('common:home'),href:'/'},{etiket:t('common:domain'),href:'/domainler'},{etiket:domain?.alan_adi||'...',href:`/abonelikler/${id}`},{etiket:t('title')}]} /><h1 className="text-2xl font-semibold text-slate-900 dark:text-slate-100 mb-1">{t('title')}</h1><p className="text-sm text-slate-500 dark:text-slate-400 mb-4">{t('desc')}</p>
 {hata&&<div className="mb-3 px-3 py-2 bg-red-50 border border-red-200 rounded-lg text-sm text-red-700">{hata}</div>}{ok&&<div className="mb-3 px-3 py-2 bg-emerald-50 border border-emerald-200 rounded-lg text-sm text-emerald-700">{ok}</div>}<div className="bg-amber-50 dark:bg-amber-900/10 border border-amber-200 dark:border-amber-800/40 rounded-2xl p-4 mb-4 text-xs text-amber-800 dark:text-amber-300">{t('info_box')}</div>
 {!ortam?<div className="bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-2xl p-5 shadow-sm"><label className="block text-sm font-medium mb-2">{t('hostname')}</label><div className="flex gap-2"><input value={alanAdi} onChange={e=>setAlanAdi(e.target.value)} className="flex-1 px-3 py-2 border rounded-lg dark:bg-slate-900 dark:border-slate-600"/><button onClick={olustur} disabled={busy||!alanAdi} className="px-4 py-2 bg-slate-900 text-white rounded-lg disabled:opacity-50">{busy?t('creating'):t('create_button')}</button></div></div>:
 <div className="space-y-4"><div className="bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-2xl p-5 shadow-sm"><div className="flex justify-between"><div><div className="font-semibold">{ortam.alan_adi}</div><div className="text-xs text-slate-500 mt-1">{t('created_at',{date:ortam.olusturma})}{ortam.son_push&&` · ${t('last_push',{date:ortam.son_push})}`}</div></div><a href={`http://${ortam.alan_adi}`} target="_blank" rel="noreferrer" className="text-sm text-brand-600">{t('open')} ↗</a></div></div><div className="bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-2xl p-5 shadow-sm"><h3 className="font-semibold mb-3">{t('push_title')}</h3><div className="flex gap-6 mb-4"><label><input type="checkbox" checked={dosyalar} onChange={e=>setDosyalar(e.target.checked)} className="mr-2"/>{t('files')}</label><label><input type="checkbox" checked={veritabani} onChange={e=>setVeritabani(e.target.checked)} className="mr-2"/>{t('database')}</label></div><div className="flex gap-2"><button onClick={push} disabled={busy||(!dosyalar&&!veritabani)} className="px-4 py-2 bg-emerald-600 text-white rounded-lg disabled:opacity-50">{busy?t('working'):t('push_button')}</button><button onClick={sil} disabled={busy} className="px-4 py-2 border border-red-300 text-red-600 rounded-lg">{t('delete_button')}</button></div></div></div>}<div className="mt-4"><Link to={`/abonelikler/${id}`} className="text-sm text-brand-600">{t('back_to_subscription')}</Link></div></div>}
