import { useCallback, useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import Breadcrumb from '@/components/Breadcrumb'
import EmptyState from '@/components/EmptyState'
import { api, apiHata } from '@/lib/api'

type Bildirim={id:number;tur:string;seviye:'dusuk'|'orta'|'yuksek'|'kritik';baslik:string;aciklama:string;kaynak:string;kaynak_sayisi:number;ip:string;domain_id:number;durum:string;ilk_at:string;son_at:string}
export default function GuvenlikBildirimleriPage(){
 const{t}=useTranslation(['GuvenlikBildirimleriPage','common']);const[liste,setListe]=useState<Bildirim[]>([]),[durum,setDurum]=useState('acik'),[hata,setHata]=useState(''),[yuk,setYuk]=useState(true)
 const getir=useCallback(()=>{setYuk(true);api.get<Bildirim[]>(`/guvenlik-bildirimleri?durum=${durum}`).then(r=>{setListe(r.data);setHata('')}).catch(e=>setHata(apiHata(e))).finally(()=>setYuk(false))},[durum]);useEffect(getir,[getir])
 async function degistir(b:Bildirim){try{await api.put(`/guvenlik-bildirimleri/${b.id}`,{durum:b.durum==='acik'?'cozuldu':'acik'});getir()}catch(e){setHata(apiHata(e))}}
 const renk={kritik:'border-red-300 bg-red-50 dark:border-red-900 dark:bg-red-950/30',yuksek:'border-amber-300 bg-amber-50 dark:border-amber-900 dark:bg-amber-950/30',orta:'border-blue-300 bg-blue-50 dark:border-blue-900 dark:bg-blue-950/30',dusuk:'border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900'}
 return <div className="px-6 py-5"><Breadcrumb items={[{etiket:t('common:home'),href:'/'},{etiket:t('GuvenlikBildirimleriPage:title')}]}/><div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-semibold">{t('GuvenlikBildirimleriPage:title')}</h1><p className="mt-1 text-sm text-slate-500">{t('GuvenlikBildirimleriPage:subtitle')}</p></div><div className="flex rounded-lg border dark:border-slate-700">{['acik','cozuldu'].map(x=><button key={x} onClick={()=>setDurum(x)} className={`px-3 py-2 text-sm ${durum===x?'bg-slate-900 text-white dark:bg-white dark:text-slate-900':''}`}>{t(`GuvenlikBildirimleriPage:${x}`)}</button>)}</div></div>{hata&&<div className="mb-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{hata}</div>}{yuk?<div className="py-12 text-center text-slate-400">{t('common:loading')}</div>:liste.length===0?<EmptyState baslik={t('GuvenlikBildirimleriPage:empty')} aciklama={t('GuvenlikBildirimleriPage:empty_desc')}/>:<div className="space-y-3">{liste.map(b=><div key={b.id} className={`rounded-xl border p-4 ${renk[b.seviye]}`}><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><span className="rounded px-2 py-0.5 text-xs font-semibold uppercase">{t(`GuvenlikBildirimleriPage:levels.${b.seviye}`)}</span><span className="text-xs text-slate-500">{b.kaynak} · {b.kaynak_sayisi}</span></div><h2 className="mt-2 font-semibold">{b.baslik}</h2><p className="mt-1 text-sm text-slate-600 dark:text-slate-300">{b.aciklama}</p><div className="mt-2 text-xs text-slate-500">{b.ilk_at} → {b.son_at}{b.ip&&` · ${b.ip}`}</div></div><button onClick={()=>degistir(b)} className="whitespace-nowrap rounded-lg border border-slate-300 px-3 py-1.5 text-xs dark:border-slate-600">{b.durum==='acik'?t('GuvenlikBildirimleriPage:resolve'):t('GuvenlikBildirimleriPage:reopen')}</button></div></div>)}</div>}</div>
}
